<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pendidikan;

class PendidikanSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $pendidikans = [
            // ── Pendidikan Dasar & Menengah ──────────────────────────────────
            'SD',
            'SMP',
            'SMA',
            'SMK',

            // ── Rumpun Komputer & Teknologi ──────────────────────────────────
            'S1 Ilmu Komputer',
            'S1 Teknik Informatika',
            'S1 Sistem Informasi',
            'S1 Teknologi Informasi',
            'S1 Teknik Komputer',
            'S1 Rekayasa Perangkat Lunak',
            'S1 Sains Data',
            'S1 Cyber Security',
            'S1 Artificial Intelligence',
            'S1 Informatika Medis',
            'S1 Teknologi Game',
            'S1 Sistem Komputer',
            'S1 Jaringan Komputer',
            'S1 Komputasi Awan',
            'S1 Multimedia',
            'S1 Animasi',
            'S1 Teknologi Rekayasa Multimedia',
            'S1 Teknologi Rekayasa Internet',
            'S1 Teknologi Rekayasa Komputer',
            'S1 Manajemen Informatika',
            'S1 Teknik Telekomunikasi',
            'S1 Teknologi Digital',
            'S1 Data Science',
            'S1 Machine Learning',
            'S1 Internet of Things',
            'S1 Software Engineering',
            'S1 Computer Engineering',
            'S1 Visual Communication Technology',

            // ── Rumpun Teknik ────────────────────────────────────────────────
            'S1 Teknik Sipil',
            'S1 Teknik Mesin',
            'S1 Teknik Elektro',
            'S1 Teknik Industri',
            'S1 Teknik Kimia',
            'S1 Teknik Lingkungan',
            'S1 Teknik Geologi',
            'S1 Teknik Geodesi',
            'S1 Teknik Arsitektur',
            'S1 Teknik Perminyakan',
            'S1 Teknik Pertambangan',
            'S1 Teknik Metalurgi',
            'S1 Teknik Material',
            'S1 Teknik Nuklir',
            'S1 Teknik Perkapalan',
            'S1 Teknik Kelautan',
            'S1 Teknik Dirgantara',
            'S1 Teknik Aeronautika',
            'S1 Teknik Biomedis',
            'S1 Teknik Fisika',
            'S1 Teknik Otomotif',
            'S1 Teknik Pengairan',
            'S1 Teknik Energi Terbarukan',
            'S1 Teknik Pangan',
            'S1 Teknik Transportasi',
            'S1 Teknik Mekatronika',
            'S1 Teknik Robotika',
            'S1 Teknik Industri Pertahanan',
            'S1 Teknik Keselamatan',
            'S1 Rekayasa Infrastruktur',
            'S1 Rekayasa Hayati',
            'S1 Teknologi Bioproses',
            'S1 Teknik Tekstil',
            'S1 Teknik Refrigerasi',
            'S1 Teknik Konversi Energi',
            'S1 Teknik Alat Berat',
            'S1 Teknik Listrik',
            'S1 Teknik Bangunan',
            'S1 Teknik Rel Kereta Api',
            'S1 Teknik Jalan dan Jembatan',
            'S1 Teknik Manufaktur',
            'S1 Teknik Produksi',

            // ── Rumpun Kedokteran & Kesehatan ────────────────────────────────
            'S1 Kedokteran',
            'S1 Pendidikan Dokter',
            'S1 Kedokteran Gigi',
            'S1 Kedokteran Hewan',
            'S1 Farmasi',
            'S1 Ilmu Keperawatan',
            'S1 Kebidanan',
            'S1 Kesehatan Masyarakat',
            'S1 Kesehatan Lingkungan',
            'S1 Ilmu Gizi',
            'S1 Fisioterapi',
            'S1 Okupasi Terapi',
            'S1 Radiologi',
            'S1 Radioterapi',
            'S1 Teknologi Laboratorium Medis',
            'S1 Analis Kesehatan',
            'S1 Rekam Medis',
            'S1 Teknik Radiodiagnostik',
            'S1 Keselamatan dan Kesehatan Kerja',
            'S1 Administrasi Rumah Sakit',
            'S1 Manajemen Pelayanan Rumah Sakit',
            'S1 Biomedis',
            'S1 Bioteknologi Kesehatan',
            'S1 Epidemiologi',
            'S1 Promosi Kesehatan',
            'S1 Terapi Wicara',
            'S1 Optometri',
            'S1 Keperawatan Gigi',
            'S1 Nutrisi dan Teknologi Pangan',
            'S1 Akupunktur',
            'S1 Psikologi Klinis',
            'S1 Kesehatan Reproduksi',
            'S1 Ilmu Kedokteran Dasar',
            'S1 Kedokteran Forensik',

            // ── Rumpun Ekonomi & Bisnis ──────────────────────────────────────
            'S1 Manajemen',
            'S1 Akuntansi',
            'S1 Ekonomi Pembangunan',
            'S1 Ilmu Ekonomi',
            'S1 Bisnis Digital',
            'S1 Kewirausahaan',
            'S1 Administrasi Bisnis',
            'S1 Administrasi Niaga',
            'S1 Ekonomi Syariah',
            'S1 Perbankan Syariah',
            'S1 Keuangan dan Perbankan',
            'S1 Perpajakan',
            'S1 Manajemen Keuangan',
            'S1 Manajemen Pemasaran',
            'S1 Manajemen SDM',
            'S1 Ekonomi Islam',
            'S1 Bisnis Internasional',
            'S1 Logistik Bisnis',
            'S1 Manajemen Ritel',
            'S1 Manajemen Bisnis',
            'S1 Manajemen Perhotelan',
            'S1 Manajemen Pariwisata',
            'S1 Aktuaria',
            'S1 Statistika Bisnis',
            'S1 Ekonomi Kreatif',
            'S1 Bisnis Hospitality',
            'S1 Supply Chain Management',
            'S1 Manajemen Event',
            'S1 Manajemen Aset',
            'S1 Manajemen Risiko',
            'S1 Fintech',
            'S1 Digital Marketing',

            // ── Rumpun Hukum, Politik & Sosial ──────────────────────────────
            'S1 Ilmu Hukum',
            'S1 Hukum Bisnis',
            'S1 Hukum Tata Negara',
            'S1 Hukum Internasional',
            'S1 Hukum Ekonomi Syariah',
            'S1 Kriminologi',
            'S1 Ilmu Politik',
            'S1 Hubungan Internasional',
            'S1 Administrasi Negara',
            'S1 Administrasi Publik',
            'S1 Administrasi Pemerintahan',
            'S1 Sosiologi',
            'S1 Antropologi',
            'S1 Kesejahteraan Sosial',
            'S1 Ilmu Komunikasi',
            'S1 Jurnalistik',
            'S1 Penyiaran',
            'S1 Public Relations',
            'S1 Periklanan',
            'S1 Broadcasting',
            'S1 Kajian Gender',
            'S1 Kajian Wilayah',
            'S1 Kajian Terorisme',
            'S1 Ilmu Pemerintahan',
            'S1 Politik Islam',
            'S1 Diplomasi',
            'S1 Intelijen',
            'S1 Keamanan Nasional',
            'S1 Kepolisian',
            'S1 Pertahanan Negara',
            'S1 Manajemen Kebijakan Publik',
            'S1 Studi Perdamaian',

            // ── Rumpun Pendidikan & Keguruan ─────────────────────────────────
            'S1 Pendidikan Guru SD',
            'S1 Pendidikan Anak Usia Dini',
            'S1 Pendidikan Bahasa Indonesia',
            'S1 Pendidikan Bahasa Inggris',
            'S1 Pendidikan Bahasa Arab',
            'S1 Pendidikan Bahasa Jepang',
            'S1 Pendidikan Bahasa Korea',
            'S1 Pendidikan Bahasa Jerman',
            'S1 Pendidikan Matematika',
            'S1 Pendidikan Fisika',
            'S1 Pendidikan Kimia',
            'S1 Pendidikan Biologi',
            'S1 Pendidikan Sejarah',
            'S1 Pendidikan Geografi',
            'S1 Pendidikan Ekonomi',
            'S1 Pendidikan Akuntansi',
            'S1 Pendidikan Sosiologi',
            'S1 Pendidikan Teknik Mesin',
            'S1 Pendidikan Teknik Elektro',
            'S1 Pendidikan Teknik Informatika',
            'S1 Pendidikan Tata Boga',
            'S1 Pendidikan Tata Busana',
            'S1 Pendidikan Seni Musik',
            'S1 Pendidikan Seni Tari',
            'S1 Pendidikan Seni Rupa',
            'S1 Pendidikan Jasmani',
            'S1 Pendidikan Kepelatihan Olahraga',
            'S1 Bimbingan Konseling',
            'S1 Teknologi Pendidikan',
            'S1 Administrasi Pendidikan',
            'S1 Manajemen Pendidikan',
            'S1 Pendidikan Luar Biasa',
            'S1 Pendidikan Luar Sekolah',
            'S1 Pendidikan Agama Islam',
            'S1 Pendidikan Agama Kristen',
            'S1 Pendidikan Agama Hindu',
            'S1 Pendidikan Agama Buddha',

            // ── Rumpun Bahasa & Sastra ───────────────────────────────────────
            'S1 Sastra Indonesia',
            'S1 Sastra Inggris',
            'S1 Sastra Jepang',
            'S1 Sastra Korea',
            'S1 Sastra Arab',
            'S1 Sastra Mandarin',
            'S1 Sastra Jerman',
            'S1 Sastra Perancis',
            'S1 Sastra Rusia',
            'S1 Sastra Jawa',
            'S1 Sastra Sunda',
            'S1 Sastra Bali',
            'S1 Sastra Minangkabau',
            'S1 Linguistik',
            'S1 Filologi',
            'S1 Penerjemahan',
            'S1 Bahasa dan Kebudayaan Korea',
            'S1 Bahasa dan Sastra Arab',
            'S1 Bahasa dan Sastra Indonesia',
            'S1 Bahasa dan Sastra Inggris',
            'S1 Kajian Sastra',
            'S1 Kajian Budaya',

            // ── Rumpun Seni & Desain ─────────────────────────────────────────
            'S1 Desain Komunikasi Visual',
            'S1 Desain Interior',
            'S1 Desain Produk',
            'S1 Seni Rupa',
            'S1 Seni Musik',
            'S1 Seni Tari',
            'S1 Seni Teater',
            'S1 Film dan Televisi',
            'S1 Fotografi',
            'S1 Animasi',
            'S1 Kriya Seni',
            'S1 Seni Karawitan',
            'S1 Etnomusikologi',
            'S1 Fashion Design',
            'S1 Tata Busana',
            'S1 Tata Rias',
            'S1 Tata Artistik',
            'S1 Perfilman',
            'S1 Broadcasting Seni',
            'S1 Desain Grafis',
            'S1 Game Art',
            'S1 Seni Pedalangan',
            'S1 Seni Murni',

            // ── Rumpun Pertanian, Kehutanan & Perikanan ──────────────────────
            'S1 Agribisnis',
            'S1 Agroteknologi',
            'S1 Agronomi',
            'S1 Ilmu Tanah',
            'S1 Proteksi Tanaman',
            'S1 Teknologi Pangan',
            'S1 Teknologi Hasil Pertanian',
            'S1 Teknologi Industri Pertanian',
            'S1 Peternakan',
            'S1 Nutrisi Ternak',
            'S1 Produksi Ternak',
            'S1 Budidaya Perairan',
            'S1 Akuakultur',
            'S1 Ilmu Kelautan',
            'S1 Teknologi Perikanan',
            'S1 Manajemen Sumber Daya Perairan',
            'S1 Kehutanan',
            'S1 Konservasi Hutan',
            'S1 Teknologi Hasil Hutan',
            'S1 Penyuluhan Pertanian',
            'S1 Bioteknologi Pertanian',
            'S1 Agroekoteknologi',
            'S1 Perkebunan',
            'S1 Hortikultura',
            'S1 Pemuliaan Tanaman',

            // ── Rumpun Agama ─────────────────────────────────────────────────
            'S1 Ilmu Al-Qur\'an dan Tafsir',
            'S1 Hadis',
            'S1 Aqidah dan Filsafat Islam',
            'S1 Hukum Keluarga Islam',
            'S1 Hukum Ekonomi Syariah',
            'S1 Perbandingan Mazhab',
            'S1 Komunikasi Penyiaran Islam',
            'S1 Bimbingan Penyuluhan Islam',
            'S1 Manajemen Dakwah',
            'S1 Pengembangan Masyarakat Islam',
            'S1 Pendidikan Islam',
            'S1 Teologi Islam',
            'S1 Filsafat Agama',
            'S1 Studi Agama-Agama',
            'S1 Pastoral',
            'S1 Teologi Kristen',
            'S1 Pendidikan Agama Katolik',
            'S1 Pendidikan Keagamaan Buddha',
            'S1 Pendidikan Hindu',
            'S1 Ushuluddin',

            // ── Rumpun Pariwisata & Hospitality ─────────────────────────────
            'S1 Pariwisata',
            'S1 Perhotelan',
            'S1 Usaha Perjalanan Wisata',
            'S1 Hospitality',
            'S1 Culinary Art',
            'S1 Seni Kuliner',
            'S1 Tata Boga',
            'S1 Event Management',
            'S1 Manajemen Konvensi',
            'S1 Travel Business',
            'S1 Kapal Pesiar',
            'S1 Destinasi Pariwisata',
            'S1 Ekowisata',
            'S1 Wisata Bahari',

            // ── Rumpun Maritim & Transportasi ───────────────────────────────
            'S1 Nautika',
            'S1 Teknika',
            'S1 Transportasi Laut',
            'S1 Manajemen Pelabuhan',
            'S1 Pelayaran',
            'S1 Transportasi Udara',
            'S1 Manajemen Bandar Udara',
            'S1 Teknik Penerbangan',
            'S1 Operasi Pesawat Udara',
            'S1 Manajemen Transportasi',
            'S1 Logistik',
            'S1 Perkeretaapian',
            'S1 Teknik Keselamatan Transportasi',

            // ── Rumpun Matematika & Sains ────────────────────────────────────
            'S1 Matematika',
            'S1 Statistika',
            'S1 Aktuaria',
            'S1 Fisika',
            'S1 Kimia',
            'S1 Biologi',
            'S1 Astronomi',
            'S1 Geofisika',
            'S1 Meteorologi',
            'S1 Oseanografi',
            'S1 Biokimia',
            'S1 Mikrobiologi',
            'S1 Bioteknologi',
            'S1 Nanoteknologi',
            'S1 Sains Lingkungan',
            'S1 Sains Aktuaria',
            'S1 Fisika Medis',

            // ── D3 ───────────────────────────────────────────────────────────
            'D3 Teknik Informatika',
            'D3 Akuntansi',
            'D3 Kebidanan',
            'D3 Keperawatan',
            'D3 Farmasi',
            'D3 Perhotelan',

            // ── D4 ───────────────────────────────────────────────────────────
            'D4 Teknologi Rekayasa Komputer',
            'D4 Teknologi Rekayasa Otomotif',
            'D4 Akuntansi',
            'D4 Manajemen Bisnis',
            'D4 Teknologi Rekayasa Multimedia',
            'D4 Teknik Mesin Produksi',
            'D4 Teknologi Rekayasa Energi',
            'D4 Rekayasa Keamanan Siber',
            'D4 Bisnis Digital',
            'D4 Desain Grafis',
            'D4 Animasi',

            // ── S2 ───────────────────────────────────────────────────────────
            'S2 Ilmu Komputer',
            'S2 Teknik Informatika',
            'S2 Sistem Informasi',
            'S2 Manajemen',
            'S2 Akuntansi',
            'S2 Ilmu Hukum',
            'S2 Ilmu Ekonomi',
            'S2 Administrasi Publik',
            'S2 Ilmu Komunikasi',
            'S2 Pendidikan',
            'S2 Teknik Sipil',
            'S2 Teknik Mesin',
            'S2 Teknik Elektro',
            'S2 Kesehatan Masyarakat',
            'S2 Ilmu Keperawatan',
            'S2 Farmasi',
            'S2 Kedokteran',
            'S2 Psikologi',
            'S2 Sosiologi',
            'S2 Ilmu Politik',
            'S2 Hubungan Internasional',
            'S2 Linguistik',
            'S2 Matematika',
            'S2 Fisika',
            'S2 Kimia',
            'S2 Biologi',
            'S2 Agribisnis',
            'S2 Kehutanan',
            'S2 Kelautan',
            'S2 Pariwisata',

            // ── S3 ───────────────────────────────────────────────────────────
            'S3 Ilmu Komputer',
            'S3 Teknik Informatika',
            'S3 Manajemen',
            'S3 Ilmu Hukum',
            'S3 Ilmu Ekonomi',
            'S3 Administrasi Publik',
            'S3 Ilmu Komunikasi',
            'S3 Pendidikan',
            'S3 Teknik Sipil',
            'S3 Teknik Mesin',
            'S3 Kesehatan Masyarakat',
            'S3 Kedokteran',
            'S3 Psikologi',
            'S3 Sosiologi',
            'S3 Matematika',
            'S3 Fisika',
            'S3 Kimia',
            'S3 Biologi',

            // ── Profesi ──────────────────────────────────────────────────────
            'Profesi Dokter',
            'Profesi Dokter Gigi',
            'Profesi Ners',
            'Profesi Apoteker',
            'Profesi Akuntan',
            'Profesi Insinyur',
            'Pendidikan Profesi Guru',
            'Profesi Psikolog',
            'Profesi Advokat',
            'Profesi Notaris',
        ];

        $total = 0;
        foreach ($pendidikans as $nama) {
            Pendidikan::firstOrCreate(['nama_pendidikan' => $nama]);
            $total++;
        }

        $this->command->info("PendidikanSeeder: {$total} data pendidikan berhasil di-seed.");
    }
}
